name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

    - name: Install additional Android components
      run: |
        export JAVA_HOME=${{ env.JAVA_HOME_17_X64 }}
        # Install required SDK components
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2" "platforms;android-33" "ndk;23.2.8568313" "platform-tools"
        # Verify AIDL installation
        ls -la $ANDROID_HOME/build-tools/33.0.2/
        echo "AIDL location: $ANDROID_HOME/build-tools/33.0.2/aidl"
      env:
        SKIP_JDK_VERSION_CHECK: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential libltdl-dev
        pip3 install --upgrade pip setuptools wheel
        pip3 install buildozer cython==0.29.33

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Cache Buildozer cache directory
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-cache-${{ hashFiles('**/buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-cache-

    - name: Build with Buildozer
      run: |
        export JAVA_HOME=${{ env.JAVA_HOME_17_X64 }}
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/23.2.8568313
        export PATH=$PATH:$ANDROID_HOME/build-tools/33.0.2:$ANDROID_HOME/platform-tools
        
        # Verify AIDL is accessible
        which aidl || echo "AIDL not in PATH, checking build-tools..."
        ls -la $ANDROID_HOME/build-tools/33.0.2/aidl || echo "AIDL not found in build-tools"
        
        # Accept any remaining licenses
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
        # Debug buildozer environment
        buildozer android debug -v
      env:
        SKIP_JDK_VERSION_CHECK: true

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: bin/*.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
