name: Test Workflow Trigger

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest # Using ubuntu-latest for simplicity

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Simple Test Step
      run: echo "Hello from GitHub Actions! This workflow is running."
